CREATE SEQUENCE seq_user
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_student
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_block
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_room
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_request
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_payment
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT seq_user.NEXTVAL FROM dual;

SELECT seq_student.NEXTVAL FROM dual;

SELECT seq_block.NEXTVAL FROM dual;

SELECT seq_room.NEXTVAL FROM dual;

SELECT seq_request.NEXTVAL FROM dual;

SELECT seq_payment.NEXTVAL FROM dual;